export const STATUS_TONES = {
  'not started': 'neutral',
  'in progress': 'info',
  submitted: 'warning',
  'under review': 'warning',
  approved: 'success',
  rejected: 'danger',
  'resubmission required': 'caution',
  'resubmission requested': 'caution',
  pass: 'success',
  warning: 'warning',
  fail: 'danger',
  active: 'info',
  complete: 'success',
  closed: 'neutral',
  blocked: 'danger',
  invited: 'neutral',
  critical: 'danger',
  high: 'danger',
  medium: 'warning',
  low: 'success',
}

export const STATUS_COLORS = {
  'Not Started': '#94a3b8',
  'In Progress': '#0ea5e9',
  Submitted: '#f59e0b',
  'Under Review': '#8b5cf6',
  Approved: '#10b981',
  'Resubmission Requested': '#ef4444',
  Rejected: '#f97316',
}

export const FOUNDATION_COLORS = {
  pageBackground: '#eef2f7',
  border: '#d7e0ea',
  surface: '#ffffff',
  surfaceMuted: '#f7f9fc',
  text: '#0f172a',
  textMuted: '#5b6b7f',
  brandPrimary: '#0f6d63',
  brandPrimaryHover: '#0c5e55',
  brandSecondary: '#2563eb',
  brandAccent: '#0ea5e9',
  brandSuccess: '#10b981',
  brandWarning: '#d97706',
  brandDanger: '#ef4444',
  brandCaution: '#f59e0b',
}

export const CHART_COLORS = {
  neutral: '#94a3b8',
  info: '#0ea5e9',
  warning: '#f59e0b',
  success: '#10b981',
  danger: '#ef4444',
  caution: '#f97316',
  brand: '#2563eb',
  brandDark: '#0f6d63',
  environmental: '#1D9E75',
  social: '#7F77DD',
  governance: '#BA7517',
  combined: '#378ADD',
  scope1: '#ef4444',
  scope2: '#0ea5e9',
  scope3: '#f59e0b',
  renewable: '#10b981',
  women: '#10b981',
  men: '#0ea5e9',
  nonBinary: '#c084fc',
  pink: '#ec4899',
  purple: '#7c3aed',
  violet: '#a855f7',
}

export const PILLAR_COLORS = {
  E: CHART_COLORS.environmental,
  S: CHART_COLORS.social,
  G: CHART_COLORS.governance,
}
