export const CONFIDENCE_OPTIONS = ['Measured', 'Estimated', 'Not Available']

export const ESG_FORM_SECTIONS = [
  {
    key: 'environmental',
    title: 'Environmental',
    description: 'Capture emissions, energy, water, waste, and air quality metrics.',
    fields: [
      {
        name: 'scope_1_emissions',
        label: 'Scope 1 emissions',
        type: 'number',
        step: '0.01',
        min: 0,
        unit: 'tCO2e',
        help: 'Direct greenhouse gas emissions from company-controlled sources.',
      },
      {
        name: 'scope_2_location_based',
        label: 'Scope 2 emissions (location-based)',
        type: 'number',
        step: '0.01',
        min: 0,
        unit: 'tCO2e',
        help: 'Purchased electricity emissions using location-based methodology.',
      },
      {
        name: 'scope_2_market_based',
        label: 'Scope 2 emissions (market-based)',
        type: 'number',
        step: '0.01',
        min: 0,
        unit: 'tCO2e',
        help: 'Purchased electricity emissions using market-based methodology.',
      },
      {
        name: 'scope_3_emissions',
        label: 'Scope 3 emissions',
        type: 'number',
        step: '0.01',
        min: 0,
        unit: 'tCO2e',
        help: 'Indirect emissions across the company value chain.',
      },
      {
        name: 'total_ghg_emissions',
        label: 'Total GHG emissions',
        type: 'number',
        step: '0.01',
        min: 0,
        unit: 'tCO2e',
        help: 'Total of Scope 1, 2, and 3 emissions.',
      },
      {
        name: 'reduction_target_percent',
        label: 'Reduction target',
        type: 'number',
        step: '0.01',
        min: 0,
        max: 100,
        unit: '%',
        help: 'Percentage reduction target for emissions.',
      },
      {
        name: 'reduction_target_year',
        label: 'Reduction target year',
        type: 'number',
        min: 2026,
        unit: 'Year',
        help: 'Target year for the emissions reduction commitment.',
      },
      {
        name: 'reduction_strategy_description',
        label: 'Reduction strategy description',
        type: 'textarea',
        help: 'Describe the strategy for meeting the emissions reduction target.',
      },
      {
        name: 'total_energy_consumption',
        label: 'Total energy consumption',
        type: 'number',
        step: '0.01',
        min: 0,
        unit: 'MWh',
        help: 'Total energy consumed during the reporting period.',
      },
      {
        name: 'renewable_energy_consumption',
        label: 'Renewable energy consumption',
        type: 'number',
        step: '0.01',
        min: 0,
        unit: 'MWh',
        help: 'Energy sourced from renewables during the reporting period.',
      },
      {
        name: 'total_water_withdrawal',
        label: 'Total water withdrawal',
        type: 'number',
        step: '0.01',
        min: 0,
        unit: 'm3',
        help: 'Total water withdrawn during the reporting period.',
      },
      {
        name: 'water_recycled_reused',
        label: 'Water recycled or reused',
        type: 'number',
        step: '0.01',
        min: 0,
        unit: 'm3',
        help: 'Volume of water recycled or reused.',
      },
      {
        name: 'total_waste_generated',
        label: 'Total waste generated',
        type: 'number',
        step: '0.01',
        min: 0,
        unit: 'Tonnes',
        help: 'Total waste generated during the reporting period.',
      },
      {
        name: 'waste_diverted_from_landfill',
        label: 'Waste diverted from landfill',
        type: 'number',
        step: '0.01',
        min: 0,
        unit: 'Tonnes',
        help: 'Waste diverted through recycling, reuse, or recovery.',
      },
      {
        name: 'hazardous_waste_generated',
        label: 'Hazardous waste generated',
        type: 'number',
        step: '0.01',
        min: 0,
        unit: 'Tonnes',
        help: 'Hazardous waste generated during the reporting period.',
      },
      {
        name: 'air_quality_control_measures',
        label: 'Air quality control measures in place',
        type: 'select',
        options: ['Yes', 'No'],
        help: 'Confirm whether air quality control measures are implemented.',
      },
      {
        name: 'nox_sox_emissions',
        label: 'NOx / SOx emissions',
        type: 'number',
        step: '0.01',
        min: 0,
        unit: 'Tonnes',
        help: 'Report NOx / SOx emissions when applicable.',
      },
    ],
  },
  {
    key: 'social',
    title: 'Social',
    description: 'Track safety, workforce, and community metrics.',
    fields: [
      {
        name: 'whs_policy_in_place',
        label: 'WHS policy in place',
        type: 'select',
        options: ['Yes', 'No'],
        help: 'Confirm whether a work health and safety policy exists.',
      },
      {
        name: 'whs_policy_document_reference',
        label: 'WHS policy document reference',
        type: 'text',
        help: 'Enter the file name or internal reference for the WHS policy document.',
      },
      {
        name: 'trifr',
        label: 'TRIFR',
        type: 'number',
        step: '0.01',
        min: 0,
        unit: 'Rate',
        help: 'Total recordable injury frequency rate.',
      },
      {
        name: 'total_fatalities',
        label: 'Total fatalities',
        type: 'number',
        min: 0,
        step: '1',
        unit: 'Count',
        help: 'Number of fatalities recorded during the reporting period.',
      },
      {
        name: 'total_lost_time_injuries',
        label: 'Total lost time injuries',
        type: 'number',
        min: 0,
        step: '1',
        unit: 'Count',
        help: 'Number of lost time injuries recorded.',
      },
      {
        name: 'total_incidents_reported',
        label: 'Total incidents reported',
        type: 'number',
        min: 0,
        step: '1',
        unit: 'Count',
        help: 'Total reported workplace incidents.',
      },
      {
        name: 'total_employees_fte',
        label: 'Total employees (FTE)',
        type: 'number',
        min: 1,
        step: '1',
        unit: 'Count',
        help: 'Total full-time equivalent employees.',
      },
      {
        name: 'employee_turnover_rate',
        label: 'Employee turnover rate',
        type: 'number',
        step: '0.01',
        min: 0,
        max: 100,
        unit: '%',
        help: 'Percentage employee turnover rate for the reporting period.',
      },
      {
        name: 'female_representation_percent',
        label: 'Female representation',
        type: 'number',
        step: '0.01',
        min: 0,
        max: 100,
        unit: '%',
        help: 'Percentage of employees identifying as female.',
      },
      {
        name: 'female_leadership_representation_percent',
        label: 'Female representation in leadership',
        type: 'number',
        step: '0.01',
        min: 0,
        max: 100,
        unit: '%',
        help: 'Percentage of leadership positions held by women.',
      },
      {
        name: 'community_investment_spend',
        label: 'Community investment or spend',
        type: 'number',
        step: '0.01',
        min: 0,
        unit: 'AUD $',
        help: 'Community investment spend during the reporting period.',
      },
    ],
  },
  {
    key: 'governance',
    title: 'Governance',
    description: 'Cover policies, oversight, cybersecurity, ethics, and board composition.',
    fields: [
      {
        name: 'esg_policy_in_place',
        label: 'ESG policy in place',
        type: 'select',
        options: ['Yes', 'No'],
        help: 'Confirm whether an ESG policy exists.',
      },
      {
        name: 'esg_policy_document_reference',
        label: 'ESG policy document reference',
        type: 'text',
        help: 'Enter the file name or internal reference for the ESG policy document.',
      },
      {
        name: 'board_level_esg_oversight',
        label: 'Board-level ESG oversight',
        type: 'select',
        options: ['Yes', 'No'],
        help: 'Confirm whether the board oversees ESG matters.',
      },
      {
        name: 'esg_kpis_linked_to_remuneration',
        label: 'ESG KPIs linked to remuneration',
        type: 'select',
        options: ['Yes', 'No'],
        help: 'Confirm whether ESG KPIs influence remuneration.',
      },
      {
        name: 'cybersecurity_policy_in_place',
        label: 'Cybersecurity policy in place',
        type: 'select',
        options: ['Yes', 'No'],
        help: 'Confirm whether a cybersecurity policy exists.',
      },
      {
        name: 'cybersecurity_policy_document_reference',
        label: 'Cybersecurity policy document reference',
        type: 'text',
        help: 'Enter the file name or internal reference for the cybersecurity policy document.',
      },
      {
        name: 'cyber_incidents_in_reporting_period',
        label: 'Cyber incidents in reporting period',
        type: 'number',
        min: 0,
        step: '1',
        unit: 'Count',
        help: 'Number of cybersecurity incidents during the reporting period.',
      },
      {
        name: 'anti_bribery_corruption_policy',
        label: 'Anti-bribery and corruption policy',
        type: 'select',
        options: ['Yes', 'No'],
        help: 'Confirm whether an anti-bribery and corruption policy exists.',
      },
      {
        name: 'confirmed_cases_of_corruption',
        label: 'Confirmed cases of corruption',
        type: 'number',
        min: 0,
        step: '1',
        unit: 'Count',
        help: 'Number of confirmed corruption cases.',
      },
      {
        name: 'total_board_members',
        label: 'Total board members',
        type: 'number',
        min: 1,
        step: '1',
        unit: 'Count',
        help: 'Total number of board members.',
      },
      {
        name: 'independent_board_members_percent',
        label: 'Independent board members',
        type: 'number',
        step: '0.01',
        min: 0,
        max: 100,
        unit: '%',
        help: 'Percentage of independent board members.',
      },
      {
        name: 'female_board_members_percent',
        label: 'Female board members',
        type: 'number',
        step: '0.01',
        min: 0,
        max: 100,
        unit: '%',
        help: 'Percentage of female board members.',
      },
    ],
  },
]

export const createInitialFormValues = () => {
  const values = {}

  ESG_FORM_SECTIONS.forEach((section) => {
    section.fields.forEach((field) => {
      values[field.name] = ''

      if (field.type !== 'textarea' && field.type !== 'text') {
        values[`${field.name}_confidence`] = ''
      }
    })
  })

  values.submission_notes = ''
  return values
}
