"""Baseline the v1.1.0 application schema.

Revision ID: 20260715_01
Revises:
Create Date: 2026-07-15
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "20260715_01"
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materiality_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('pillar', sa.String(), nullable=False),
    sa.Column('impact_score', sa.Float(), nullable=False),
    sa.Column('financial_score', sa.Float(), nullable=False),
    sa.Column('stakeholder_score', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materiality_topics_id'), 'materiality_topics', ['id'], unique=False)
    op.create_index(op.f('ix_materiality_topics_topic'), 'materiality_topics', ['topic'], unique=True)
    op.create_table('narrative_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audience', sa.String(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('tone', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('source_years', sa.Text(), nullable=False),
    sa.Column('source_company_count', sa.Integer(), nullable=False),
    sa.Column('source_submission_count', sa.Integer(), nullable=False),
    sa.Column('latest_source_years', sa.Text(), nullable=False),
    sa.Column('latest_source_company_count', sa.Integer(), nullable=False),
    sa.Column('latest_source_submission_count', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('cached', sa.Boolean(), nullable=False),
    sa.Column('fallback_used', sa.Boolean(), nullable=False),
    sa.Column('freshness_status', sa.String(), nullable=False),
    sa.Column('freshness_label', sa.String(), nullable=False),
    sa.Column('freshness_reason', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.String(), nullable=False),
    sa.Column('headline', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('highlights', sa.Text(), nullable=False),
    sa.Column('watchouts', sa.Text(), nullable=False),
    sa.Column('recommendations', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('framework_tags', sa.Text(), nullable=False),
    sa.Column('generated_payload', sa.Text(), nullable=False),
    sa.Column('edited_payload', sa.Text(), nullable=False),
    sa.Column('published_payload', sa.Text(), nullable=False),
    sa.Column('approved_by_role', sa.String(), nullable=True),
    sa.Column('approved_at', sa.String(), nullable=True),
    sa.Column('edited_by_role', sa.String(), nullable=True),
    sa.Column('edited_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_narrative_records_company_id'), 'narrative_records', ['company_id'], unique=False)
    op.create_index(op.f('ix_narrative_records_id'), 'narrative_records', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('COMPANY', 'MANAGER', 'INVESTOR', name='userrole', native_enum=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('auth_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_sessions_expires_at'), 'auth_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_auth_sessions_id'), 'auth_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_auth_sessions_token_hash'), 'auth_sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    op.create_table('collection_cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_year', sa.Integer(), nullable=False),
    sa.Column('submission_open_date', sa.String(), nullable=False),
    sa.Column('submission_deadline', sa.String(), nullable=False),
    sa.Column('extension_date', sa.String(), nullable=True),
    sa.Column('reminder_schedule', sa.String(), nullable=False),
    sa.Column('template_config', sa.String(), nullable=False),
    sa.Column('prefill_summary', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cycle_year')
    )
    op.create_index(op.f('ix_collection_cycles_id'), 'collection_cycles', ['id'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sector', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('asset_class', sa.String(), nullable=True),
    sa.Column('geography', sa.String(), nullable=True),
    sa.Column('client_visible', sa.String(), nullable=True),
    sa.Column('current_status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_code'), 'companies', ['code'], unique=True)
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_expires_at'), 'password_reset_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_id'), 'password_reset_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('action_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('initiative_name', sa.String(), nullable=False),
    sa.Column('target_completion_date', sa.String(), nullable=False),
    sa.Column('assigned_owner', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_plans_id'), 'action_plans', ['id'], unique=False)
    op.create_table('esg_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('pillar', sa.String(), nullable=False),
    sa.Column('metric_key', sa.String(), nullable=False),
    sa.Column('target_name', sa.String(), nullable=False),
    sa.Column('baseline_value', sa.Float(), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('target_date', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_esg_targets_company_id'), 'esg_targets', ['company_id'], unique=False)
    op.create_index(op.f('ix_esg_targets_id'), 'esg_targets', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('notification_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('dedupe_key', sa.String(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_company_id'), 'notifications', ['company_id'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_dedupe_key'), 'notifications', ['dedupe_key'], unique=True)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notifications_role'), 'notifications', ['role'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('reminder_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('sent_by_user_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('delivery_status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['cycle_id'], ['collection_cycles.id'], ),
    sa.ForeignKeyConstraint(['sent_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminder_logs_company_id'), 'reminder_logs', ['company_id'], unique=False)
    op.create_index(op.f('ix_reminder_logs_cycle_id'), 'reminder_logs', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_reminder_logs_id'), 'reminder_logs', ['id'], unique=False)
    op.create_table('submission_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['cycle_id'], ['collection_cycles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'cycle_id', name='uq_submission_draft_company_cycle')
    )
    op.create_index(op.f('ix_submission_drafts_company_id'), 'submission_drafts', ['company_id'], unique=False)
    op.create_index(op.f('ix_submission_drafts_cycle_id'), 'submission_drafts', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_submission_drafts_id'), 'submission_drafts', ['id'], unique=False)
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=True),
    sa.Column('esg_data', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['cycle_id'], ['collection_cycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_cycle_id'), 'submissions', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_submissions_id'), 'submissions', ['id'], unique=False)
    op.create_table('validation_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('reporting_year', sa.Integer(), nullable=False),
    sa.Column('flag_type', sa.String(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('issue_description', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_flags_id'), 'validation_flags', ['id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('actor_email', sa.String(), nullable=True),
    sa.Column('actor_role', sa.String(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('submission_id', sa.Integer(), nullable=True),
    sa.Column('cycle_id', sa.Integer(), nullable=True),
    sa.Column('field_name', sa.String(), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['cycle_id'], ['collection_cycles.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_actor_email'), 'audit_events', ['actor_email'], unique=False)
    op.create_index(op.f('ix_audit_events_company_id'), 'audit_events', ['company_id'], unique=False)
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_cycle_id'), 'audit_events', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_id'), 'audit_events', ['id'], unique=False)
    op.create_index(op.f('ix_audit_events_submission_id'), 'audit_events', ['submission_id'], unique=False)
    op.create_table('metric_review_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('metric_key', sa.String(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('reviewer_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', 'metric_key', name='uq_metric_comment_submission_metric')
    )
    op.create_index(op.f('ix_metric_review_comments_id'), 'metric_review_comments', ['id'], unique=False)
    op.create_index(op.f('ix_metric_review_comments_metric_key'), 'metric_review_comments', ['metric_key'], unique=False)
    op.create_index(op.f('ix_metric_review_comments_submission_id'), 'metric_review_comments', ['submission_id'], unique=False)
    op.create_table('review_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=True),
    sa.Column('reporting_year', sa.Integer(), nullable=False),
    sa.Column('review_status', sa.String(), nullable=False),
    sa.Column('reviewer_role', sa.String(), nullable=False),
    sa.Column('review_comment', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_actions_id'), 'review_actions', ['id'], unique=False)
    op.create_index(op.f('ix_review_actions_submission_id'), 'review_actions', ['submission_id'], unique=False)
    op.create_table('submission_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=True),
    sa.Column('metric_key', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['cycle_id'], ['collection_cycles.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submission_evidence_company_id'), 'submission_evidence', ['company_id'], unique=False)
    op.create_index(op.f('ix_submission_evidence_cycle_id'), 'submission_evidence', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_submission_evidence_id'), 'submission_evidence', ['id'], unique=False)
    op.create_index(op.f('ix_submission_evidence_metric_key'), 'submission_evidence', ['metric_key'], unique=False)
    op.create_index(op.f('ix_submission_evidence_submission_id'), 'submission_evidence', ['submission_id'], unique=False)
    op.create_table('submission_unlocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('unlocked_by_user_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['cycle_id'], ['collection_cycles.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.ForeignKeyConstraint(['unlocked_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submission_unlocks_company_id'), 'submission_unlocks', ['company_id'], unique=False)
    op.create_index(op.f('ix_submission_unlocks_cycle_id'), 'submission_unlocks', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_submission_unlocks_id'), 'submission_unlocks', ['id'], unique=False)
    op.create_index(op.f('ix_submission_unlocks_submission_id'), 'submission_unlocks', ['submission_id'], unique=False)
    op.create_table('assurance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=True),
    sa.Column('metric_key', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('assurance_level', sa.String(), nullable=False),
    sa.Column('conclusion', sa.Text(), nullable=True),
    sa.Column('reviewer_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['submission_evidence.id'], ),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', 'metric_key', name='uq_assurance_submission_metric')
    )
    op.create_index(op.f('ix_assurance_records_evidence_id'), 'assurance_records', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_assurance_records_id'), 'assurance_records', ['id'], unique=False)
    op.create_index(op.f('ix_assurance_records_metric_key'), 'assurance_records', ['metric_key'], unique=False)
    op.create_index(op.f('ix_assurance_records_submission_id'), 'assurance_records', ['submission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assurance_records_submission_id'), table_name='assurance_records')
    op.drop_index(op.f('ix_assurance_records_metric_key'), table_name='assurance_records')
    op.drop_index(op.f('ix_assurance_records_id'), table_name='assurance_records')
    op.drop_index(op.f('ix_assurance_records_evidence_id'), table_name='assurance_records')
    op.drop_table('assurance_records')
    op.drop_index(op.f('ix_submission_unlocks_submission_id'), table_name='submission_unlocks')
    op.drop_index(op.f('ix_submission_unlocks_id'), table_name='submission_unlocks')
    op.drop_index(op.f('ix_submission_unlocks_cycle_id'), table_name='submission_unlocks')
    op.drop_index(op.f('ix_submission_unlocks_company_id'), table_name='submission_unlocks')
    op.drop_table('submission_unlocks')
    op.drop_index(op.f('ix_submission_evidence_submission_id'), table_name='submission_evidence')
    op.drop_index(op.f('ix_submission_evidence_metric_key'), table_name='submission_evidence')
    op.drop_index(op.f('ix_submission_evidence_id'), table_name='submission_evidence')
    op.drop_index(op.f('ix_submission_evidence_cycle_id'), table_name='submission_evidence')
    op.drop_index(op.f('ix_submission_evidence_company_id'), table_name='submission_evidence')
    op.drop_table('submission_evidence')
    op.drop_index(op.f('ix_review_actions_submission_id'), table_name='review_actions')
    op.drop_index(op.f('ix_review_actions_id'), table_name='review_actions')
    op.drop_table('review_actions')
    op.drop_index(op.f('ix_metric_review_comments_submission_id'), table_name='metric_review_comments')
    op.drop_index(op.f('ix_metric_review_comments_metric_key'), table_name='metric_review_comments')
    op.drop_index(op.f('ix_metric_review_comments_id'), table_name='metric_review_comments')
    op.drop_table('metric_review_comments')
    op.drop_index(op.f('ix_audit_events_submission_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_cycle_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_company_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_email'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_validation_flags_id'), table_name='validation_flags')
    op.drop_table('validation_flags')
    op.drop_index(op.f('ix_submissions_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_cycle_id'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_submission_drafts_id'), table_name='submission_drafts')
    op.drop_index(op.f('ix_submission_drafts_cycle_id'), table_name='submission_drafts')
    op.drop_index(op.f('ix_submission_drafts_company_id'), table_name='submission_drafts')
    op.drop_table('submission_drafts')
    op.drop_index(op.f('ix_reminder_logs_id'), table_name='reminder_logs')
    op.drop_index(op.f('ix_reminder_logs_cycle_id'), table_name='reminder_logs')
    op.drop_index(op.f('ix_reminder_logs_company_id'), table_name='reminder_logs')
    op.drop_table('reminder_logs')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_role'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_dedupe_key'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_company_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_esg_targets_id'), table_name='esg_targets')
    op.drop_index(op.f('ix_esg_targets_company_id'), table_name='esg_targets')
    op.drop_table('esg_targets')
    op.drop_index(op.f('ix_action_plans_id'), table_name='action_plans')
    op.drop_table('action_plans')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_expires_at'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_code'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_collection_cycles_id'), table_name='collection_cycles')
    op.drop_table('collection_cycles')
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_token_hash'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_id'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_expires_at'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_narrative_records_id'), table_name='narrative_records')
    op.drop_index(op.f('ix_narrative_records_company_id'), table_name='narrative_records')
    op.drop_table('narrative_records')
    op.drop_index(op.f('ix_materiality_topics_topic'), table_name='materiality_topics')
    op.drop_index(op.f('ix_materiality_topics_id'), table_name='materiality_topics')
    op.drop_table('materiality_topics')
    # ### end Alembic commands ###

